### ISSUE TITLE
Adat import logikája

### ISSUE THREAD

**Issue by law909** [Code-for-Hungary/agrartamapi#3]
- [x] Sor adatok
Az id-t a program generálja. Egy sort az **id** azonosít.
Ha az **id** létezik, akkor a sor felülírásra kerül az új adatokkal.
Ha a sorban nincs megadva **id**, akkor a program újként veszi fel az adatbázisba.
Ha ismeretlen **id** van megadva, a program nem foglalkozik a sorral.

- [x] Megye
Az id itt fix, az államilag meghatározottat használjuk.
Ha az **id** létezik, akkor a megyéhez kapcsolom a sort.
Ha az **id** nem létezik vagy nincs megadva, nem kapcsolom megyéhez.

- [x] Cégcsoport
Az id-t az adatrögzítők hozzák létre. Cégcsoportot ez az **id** azonosítja.
Ha az **id** létezik, akkor a cégcsoporthoz kapcsolom a sort.
Ha az **id** nem létezik, akkor létrehozom az új cégcsoportot és hozzá kapcsolom a sort.
Ha az **id** nincs megadva, akkor nem kapcsolok a sorhoz cégcsoportot.

- [x] Támogatott entitás
Az id-t az adatrögzítők hozzák létre. Támogatott entitást ez az **id** azonosítja.
Ha az **id** létezik, akkor a támogatott entitáshoz kapcsolom a sort.
Ha az **id** nem létezik, akkor létrehozom az új tám.entitást és hozzá kapcsolom a sort.
Ha az **id** nincs megadva, akkor nem kapcsolok a sorhoz tám.entitást.

- [x] Forrás
Az id-t a program generálja, a forrást a **nevével** azonosítjuk az importban.
Ha a **név** létezik, akkor a forráshoz kapcsolom a sort.
Ha a **név** nem létezik, akkor létrehozom a forrást és hozzá kapcsolom a sort.
Ha a **név** nincs megadva, akkor a program nem foglalkozik tovább a sorral.

- [x] Alap
Az id-t a program generálja, az alapot a **nevével** azonosítjuk az importban.
Ha a **név** létezik, akkor az alaphoz kapcsolom a sort.
Ha a **név** nem létezik, akkor létrehozom az alapot és hozzá kapcsolom a sort.
Ha a **név** nincs megadva, akkor a program nem foglalkozik tovább a sorral.

- [x] Jogcím
Az id-t a program generálja, a jogcímet a **nevével** azonosítjuk az importban.
Ha a **név** létezik, akkor a jogcímhez kapcsolom a sort.
Ha a **név** nem létezik, akkor létrehozom a jogcímet és hozzá kapcsolom a sort.
Ha a **név** nincs megadva, akkor a program nem foglalkozik tovább a sorral.

**Comment by law909** [comment]
@pisipite Olvasd át kérlek, hogy jó-e így.

**Comment by pisipite** [comment]
nekem okénak tűnik.
