### ISSUE TITLE
cégcsoport, támogatott entitás error

### ISSUE THREAD

**Issue by pisipite** [Code-for-Hungary/agrartamapi#9]
ha ezek közül kiválasztok valamit, errort ad. mi lehet az ok?
![kép](https://user-images.githubusercontent.com/25430950/189087482-5cf1b97a-2c55-4fea-ae44-b188a35f753d.png)

**Comment by law909** [comment]
Üres név szűrőből is szűrőt csináltam, csak szintaktikai hibásat.
